"""Electronic fence schemas."""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator


class FenceBase(BaseModel):
    """Shared electronic fence fields."""

    name: str = Field(min_length=1, max_length=100)
    center_latitude: float
    center_longitude: float
    radius_meters: float = Field(gt=0, le=100000)
    is_active: bool = True

    @field_validator("center_latitude")
    @classmethod
    def validate_latitude(cls, value: float) -> float:
        """Ensure latitude is valid."""

        if not -90 <= value <= 90:
            raise ValueError("Latitude must be between -90 and 90")
        return value

    @field_validator("center_longitude")
    @classmethod
    def validate_longitude(cls, value: float) -> float:
        """Ensure longitude is valid."""

        if not -180 <= value <= 180:
            raise ValueError("Longitude must be between -180 and 180")
        return value


class FenceCreate(FenceBase):
    """Create fence payload."""


class FenceUpdate(FenceBase):
    """Update fence payload."""


class FenceRead(FenceBase):
    """Fence response payload."""

    id: int
    device_id: str
    user_id: int
    last_status: str
    last_transition_at: datetime | None = None

    model_config = ConfigDict(from_attributes=True)


class FenceEvaluation(BaseModel):
    """Fence evaluation result for a location."""

    fence_id: int
    fence_name: str
    distance_meters: float
    status: str
    transitioned: bool


class FenceAlert(BaseModel):
    """Alert details generated by a fence breach."""

    fence_id: int
    fence_name: str
    distance_meters: float
    message: str
