"""Electronic fence schemas."""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class FenceBase(BaseModel):
    """Shared electronic fence fields."""

    name: str = Field(min_length=1, max_length=100)
    center_latitude: float = Field(ge=-90, le=90)
    center_longitude: float = Field(ge=-180, le=180)
    radius_meters: float = Field(gt=0, le=100000)
    is_active: bool = True


class FenceCreate(FenceBase):
    """Create fence payload."""


class FenceUpdate(BaseModel):
    """Update fence payload - all fields optional for partial update."""

    name: str | None = Field(default=None, min_length=1, max_length=100)
    center_latitude: float | None = Field(default=None, ge=-90, le=90)
    center_longitude: float | None = Field(default=None, ge=-180, le=180)
    radius_meters: float | None = Field(default=None, gt=0, le=100000)
    is_active: bool | None = None


class FenceRead(FenceBase):
    """Fence response payload."""

    id: int
    device_id: str
    user_id: int
    last_status: str
    last_transition_at: datetime | None = None

    model_config = ConfigDict(from_attributes=True)


class FenceEvaluation(BaseModel):
    """Fence evaluation result for a location."""

    fence_id: int
    fence_name: str
    distance_meters: float
    status: str
    transitioned: bool


class FenceAlert(BaseModel):
    """Alert details generated by a fence breach."""

    fence_id: int
    fence_name: str
    distance_meters: float
    message: str
